### ISSUE TITLE
show CPU usage meter on Power tab

### ISSUE THREAD

**Issue by Nowaker** [virtkick/virtkick#10]
https://demo.virtkick.io/machine.html#stats

**Comment by Rush** [comment]
what's your take on implementing it?

**Comment by Rush** [comment]
UI gets the stats already but backend sends the cpu usage in relation to the amount of cores, so say 12% for 100%. We need to get number of cores so that 12% can be scaled to 100% for the UI

**Comment by malps13** [comment]
@Rush have you thought which charts library we will be using for plotting this data? I could then make some designs of how the stats should look like having in mind what will be our take on implementation. From my experience there aren't so many libraries which support RWD out of the box, so I think we have not so much to choose from.

**Comment by Nowaker** [comment]
@malps13 I reconsidered the UI, and we'll go without [these graphs](https://demo.virtkick.io/machine.html#stats) at all - they're not needed.

We'll just implement a simple progress bar like meter on Power page - just below the number of CPUs. https://demo.virtkick.com/machine.html.

**Comment by malps13** [comment]
@Nowaker OK, can you mock me some sample data we will be drawing?
