### ISSUE TITLE
empty ISO selection menu

### ISSUE THREAD

**Issue by Nowaker** [virtkick/virtkick#120]
Looks a little bit weird, it should have "None selected" or something like this. But only when nothing is selected - you shouldn't be able to check "none" from the list if you already have something.

http://upload.nowaker.net/nwkr/1421863158_none-selected.png

**Comment by malps13** [comment]
Actually @Rush had it covered using 'placeholder' attribute, but there was a typo. I will fix it and that should solve the issue.
