### ISSUE TITLE
Prepare billing module UI

### ISSUE THREAD

**Issue by malps13** [virtkick/virtkick#132]

**Comment by malps13** [comment]
I've prepared initial dashboard design:

![virtkick-demo-13-billing-dashboard](https://cloud.githubusercontent.com/assets/3458255/5929271/951bc5b6-a682-11e4-9bc7-943f70a5d95d.png)

And for mobile it may look like this:

![virtkick-demo-13-billing-dashboard-mobile](https://cloud.githubusercontent.com/assets/3458255/5929272/986bb8fc-a682-11e4-8624-dd0f3efa8eb7.png)

**Comment by malps13** [comment]
We need to design also page look in case if:

* the balance equals 0 - some nice way to inform user about this, maybe also some info if there is payment arrears
* there is no credit card info added
* invoice element look with no invoices so far

All of there should provide proper messages to user. @wozmir could you think of some messages, that i could then incorporate into the design of these states?

**Comment by wozmir** [comment]
wozmir to the rescue!

the balance equals 0:  "Not enough funds on your card to pay for this service."
payment arrear: "You have an overdue payment for invoice <date>." (if I understand this correctly)
no credit card info: "You haven't added any credit cards yet. [Click here](link) to do that now."
invoice element: "Invoices will show up here."

**Comment by malps13** [comment]
I've designed dashboard with initial messages following @wozmir suggestions. Just one details: as far as I know balance 0 is positive - because it means everything is paid. 

![virtkick-demo-13-billing-dashboard-new-github](https://cloud.githubusercontent.com/assets/3458255/5938489/f3e23c3c-a6fb-11e4-861a-a48c1fef239d.png)

I've also prepared a view after clicking "add credit card" or "edit credit card". It is a modal window with bright overlay on rest of billing module content. In mobile version, modal should slide from the right.

![virtkick-demo-13-billing-credit-card-github](https://cloud.githubusercontent.com/assets/3458255/5938519/212e2e44-a6fc-11e4-8aaa-1d69a93bc1ac.png)

**Comment by malps13** [comment]
After changing requirements I've redesigned dashboard:

![virtkick-demo-16-billing-dashboard](https://cloud.githubusercontent.com/assets/3458255/6071223/ba0ecd38-ad93-11e4-833b-d7a893d2b6c0.png)

After clicking "+" icon the payment proccess is about to start, this is how it looks like:

![virtkick-demo-16-billing-payment](https://cloud.githubusercontent.com/assets/3458255/6071224/bf0748b0-ad93-11e4-9a86-57e7899d23cc.png)

User can view current usage history by clicking on "details" link (just under balance info)

![virtkick-demo-16-billing-current-usage](https://cloud.githubusercontent.com/assets/3458255/6071229/c54d9d64-ad93-11e4-88f4-1f2f31cba928.png)

Clicking on machine icon in invoice table will show details of billing for the given period:

![virtkick-demo-16-billing-usage-history](https://cloud.githubusercontent.com/assets/3458255/6071232/c96742c4-ad93-11e4-882a-647d1b0e042a.png)

**Comment by malps13** [comment]
It turned out that I've got some concepts wrong - since invoices are for adding credits not the VM usage. So the new concepts look like this:

Dashboard:

![virtkick-demo-17-billing-dashboard](https://cloud.githubusercontent.com/assets/3458255/6073287/8dcda7a8-adac-11e4-91e6-bbf839540455.png)

Payment:

![virtkick-demo-17-billing-payment](https://cloud.githubusercontent.com/assets/3458255/6073290/95e82404-adac-11e4-8603-d1d3f0179d59.png)

Current usage:

![virtkick-demo-17-billing-current-usage](https://cloud.githubusercontent.com/assets/3458255/6073292/9b3ee5d2-adac-11e4-90e4-627591c4d6f0.png)

Invoicing history:

![virtkick-demo-17-billing-invoicing-history](https://cloud.githubusercontent.com/assets/3458255/6073293/a08d489e-adac-11e4-892d-988994fba83d.png)

**Comment by malps13** [comment]
After rethinking the way we should handle case of initial billing setup, I think we shouldn't show billing interface at all if user hasn't added billing card yet - we don't need to distract him from the most important action:

![virtkick-demo-19-billing-credit-card-1](https://cloud.githubusercontent.com/assets/3458255/6118266/34bd5042-b0bc-11e4-8c5e-82072dd1c54f.png)

Now is the trickiest part - we have to make sure user read and understand our billing model prior to entering credit card info in order to avoid misunderstanding and unpredicted transactions, which may leed to confusion and irritation.  [Note - the same action can be triggered by trying to create VM without setting up billing ] I will cover this proccess in next comment, for now let's pretend used read our guidelines and added succesfully his credit card info.

After the card is added, Billing module becomes unlocked but it still shows some empty values:

![virtkick-demo-19-billing-credit-card-2](https://cloud.githubusercontent.com/assets/3458255/6118286/6d7a6faa-b0bc-11e4-8096-cdcea8844ab3.png)

Finally, after creating some VMs billing module is fully functional:

![virtkick-demo-19-billing-credit-card-3](https://cloud.githubusercontent.com/assets/3458255/6118290/79df0e72-b0bc-11e4-9afd-593a8072ba44.png)

**Comment by Nowaker** [comment]
>  I think we shouldn't show billing interface at all if user hasn't added billing card yet

Agreed.

**Comment by malps13** [comment]
OK, so when setting up credit card for the first time we may use interactive tour with following 4 steps:

![virtkick-demo-20-billing-tour-1](https://cloud.githubusercontent.com/assets/3458255/6137055/267c0eb4-b176-11e4-8b99-4f112c852f2a.png)
![virtkick-demo-20-billing-tour-2](https://cloud.githubusercontent.com/assets/3458255/6137057/29427b88-b176-11e4-8a0b-54a464b2bd94.png)
![virtkick-demo-20-billing-tour-3](https://cloud.githubusercontent.com/assets/3458255/6137058/2aa287fc-b176-11e4-929f-fb44efea2e08.png)
![virtkick-demo-20-billing-tour-4](https://cloud.githubusercontent.com/assets/3458255/6137060/2c3dbf14-b176-11e4-93e5-cb9f3b52ede4.png)

This way we provide basic information to user - step by step, making it easier to understand. Moreover, we are also adding "skip tour" to those, who are not concerned about payment or have used Virtkick in pas (i.e with different account).

If we argee that this is the way to go, we will be needing @wozmir he to make this tour texts fun and enjoyable, not only strictly informative. Moreover, we could add some animations to the icons to better visualize 3 main points and increase user understaining and entertainment.

**Comment by malps13** [comment]
Merged, closing.
