### ISSUE TITLE
Use with existing infrastructure

### ISSUE THREAD

**Issue by tobru** [virtkick/virtkick#140]
We are already running a small virtualization infrastructure using plain libvirt (plain=no-other-cloud-orchestrator(tm)) and WebVirtMgr as webfrontend. VK looks very promising to us and the best thing would be that we could just replace WebVirtMgr with VK. I've already tried it by hacking virtkick-starter, but as #43 mentions, the feature for using multiple hypervisors is also missing.

TL;DR: We need an import mechanism for exiting hypervisors which are already managed by libvirt.

**Comment by Nowaker** [comment]
@tobru This should be possible after #43, so I'm closing this one. :)
