### ISSUE TITLE
LDAP authentication

### ISSUE THREAD

**Issue by tobru** [virtkick/virtkick#141]
Would be great to be able to authenticate using LDAP.

**Comment by Nowaker** [comment]
@tobru What is your use case? Private cloud, I believe?

**Comment by tobru** [comment]
Not only, also for having one central user database for other services our customers are able to log in to. The goal is that the customer only has one account for all services provided by us. A second goal would be to have SSO (f.e. using CAS or Shibboleth).

**Comment by Nowaker** [comment]
@tobru We won't be implementing this feature - at least in the next 6 months. Therefore I'll close it.

If you'd want to play with it, these are some hints. Virtkick uses [Devise](https://github.com/plataformatec/devise) as authentication backend. You would probably need to do some plumbing with [devise-ldap-authenticate](https://github.com/cschiewek/devise_ldap_authenticatable).

**Comment by tobru** [comment]
Ok, thanks for the pointer to Devise
