### ISSUE TITLE
virtkick/starter nodemon error

### ISSUE THREAD

**Issue by lkoenigsberger** [virtkick/virtkick#149]
Hi folks,
I get the following error when trying to start virtkick:
```
Process rails exit: 127
Process work0 exit: 127
bash: nodemon: command not found
bash: nodemon: command not found
WARNING:root:No local_settings file found.
```
Can anyone help or is that a bug?
I try to run virtkick on ubuntu 14.04 

Thanks

**Comment by Nowaker** [comment]
Hey, sorry for that. We broke it yesterday - we'll fix in a few hours.

**Comment by lkoenigsberger** [comment]
OK Thanks for the info!!

**Comment by Rush** [comment]
Should be fixed. Please do `rm -rf node_modules` and re-try the start.
