### ISSUE TITLE
Bug in machine list display

### ISSUE THREAD

**Issue by malps13** [virtkick/virtkick#152]
Machine list displayed in table on http://localhost:3000/machines  cut if there are many machines.

**Comment by malps13** [comment]
@Nowaker is it still an issue? I've tried to reproduce with 11 VM to cause the page to scroll but with no luck - all are there visible.

**Comment by Nowaker** [comment]
@malps13 I meant there's 0 pixels between the table and Chrome window border. There should be like 20px of white margin between the table and the window.
