### ISSUE TITLE
Problem about Demo on Virtkick's home page

### ISSUE THREAD

**Issue by luanvn1404** [virtkick/virtkick#156]
I already mentioned that look like Virtkick's home page changed something. Maybe 4 5 days ago. I saw that there were `Download Alpha` click. Now that was not exist.

And I wanna ask why `Demo` part wasn't active. I can't create new one machine. After I created one new machine. I didn't see that display on `Machine` instead of I only see `HTTP running...`

Look like there're something wrong, right?

**Comment by Nowaker** [comment]
@luanvn1404 The download section will be brought back soon. After the website redesign, our guys forgot to include this page.

Demo is a static HTML prototype for preview. We'll be deploying a real version once most of the essential features are in place. (We don't want people to think that creating, starting and stopping machines is all Virtkick is about)
