### ISSUE TITLE
libvirt: QEMU Driver error : unsupported configuration: Domain requires KVM, but it is not available

### ISSUE THREAD

**Issue by luanvn1404** [virtkick/virtkick#163]
I already installed on my ubuntu server from Xen. On my ubuntu, i also ran virtkick-starter by `./virtkick-start -dim`. And then I can open my browser via port 3000. Also I can create one new machine in order to test. At that time my browser shoot ouput disconnect. Then i checked log error, I received one error with following content:

`libvirt: QEMU Driver error : unsupported configuration: Domain requires KVM, but it is not available. Check that virtualization is enabled in the host BIOS, and host configuration is setup to load the kvm modules.`

`["unsupported configuration: Domain requires KVM, but it is not available. Check that virtualization is enabled in the host BIOS, and host configuration is setup to load the kvm modules."]`

Any help. I'm really appreciated. Thanks.

**Comment by Nowaker** [comment]
@luanvn1404 The reason it doesn't work is you tried running it in a Xen virtual machine. Xen doesn't support nested virtualization - simply put, it doesn't let run virtual machines in virtual machines. 

You should install Virtkick on a dedicated server. (Or in a KVM virtual machine, but nested virtualization needs to be enabled properly)

Hope this helps.

**Comment by luanvn1404** [comment]
@Nowaker Thanks about your reply. I'll try it on my workstation ubuntu.

I checked via:

```
egrep -c '(svm|vmx)' /proc/cpuinfo 
4
```

**Comment by luanvn1404** [comment]
@Nowaker I opened new one issue for my workstation ubuntu at https://github.com/virtkick/virtkick/issues/164
