### ISSUE TITLE
design custom ajax loader icon

### ISSUE THREAD

**Issue by malps13** [virtkick/virtkick#28]
As Virtkick is becoming responsive, it would be nice to design custom ajax loader icon. It should be available in different sizes - big one (for example shown when there is bigger area being loaded) and smaller one (like ajax circle near machine state). So far I have two ideas:

- random sprinkling of red pixels
- pixel rocket being build by attaching subsequent pixels

Please let me know what you thinks, any ideas appreciated ;-)

**Comment by malps13** [comment]
OK, so WIP ajax loader icon currently looks like this: http://codepen.io/malps13/full/dPNxEL/

I am thinking of simplifying it even more and leaving just "flloating circle" instead of circle being a window - have to check how it looks live in webapp.

**Comment by malps13** [comment]
@Rush I think that two rockets you've mentioned is an overshoot, I've looked at some ajax loaders out there in the Web and all of them are rather simple.

What would you say to a simple circle loader like this: http://codepen.io/malps13/full/YPVmyr/ ?

**Comment by Rush** [comment]
Looks great!

**Comment by malps13** [comment]
OK,  I've commited it to PR virtkick/virtkick-webapp#6. We may be tweaking it in the future, but I am closing it for now.
