### ISSUE TITLE
virtkick is crowdfunding

### ISSUE THREAD

**Issue by Rush** [virtkick/virtkick#55]
Thank you for starring one of our repos and sharing our enthusiasm for this project. It is thanks to you dear supporters that we have gained courage to start a crowdfunding campaign! 
https://www.indiegogo.com/projects/virtkick-take-cloud-back

When it succeeds we will be able to focus on developing virtkick. It's gonna be a great journey!

You are most welcome to follow our developments and post any comments or remarks you may have.
Thanks!

@levex @julien-f @olivierlambert @gowthamsadasivam @brennebeck @grzew @rogerlz @fazo96 @vt102 @codedaiquiri @kciesielski @geerlingguy @stoutZero @sh0b @GIANTCRAB @deedoubledub @charloco @manishjhawar @Quizp2p @muminoff @jgillich @abrongersma @sprybear @lijiangsheng1 @yhchiu @kielabokkie @webwurst @onemoz @yofreke @ykisen @flangefrog @dalareo @northox @tarek-aec @karistuck @nitemv @JFKingsley @will3942 @joubertredrat @daniviga @kenetik @JFOC @CodingWolfx @emanuelbsilva @dai @bmpvieira @codehead @seapoems @hmert @Beyondem @femnad

**Comment by Rush** [comment]
Thanks guys, closing the issue since indiegogo has ended! We now have sufficient funding to continue development and are doing it full time. Yeehaw.

**Comment by dalareo** [comment]
Congrats dudes!!! Anxiously waiting for new features!!

**Comment by brennebeck** [comment]
Not sure how I missed this but great to see that @Rush will be on this full time :+1:

**Comment by joubertredrat** [comment]
Nice job guys :)

**Comment by gowthamsadasivam** [comment]
Awesome guys. VirtKick is going to be a kick-ass tool! :+1:
