### ISSUE TITLE
provide services with packages

### ISSUE THREAD

**Issue by Stephen304** [virtkick/virtkick#75]
I have virtkick running and the biggest hassel right now is that I have to leave a terminal open SSHed into my server running ./virtkick-start. Is it planned to have a service that I would be able to start with `service virtkick start` so that it will start on boot and start/restart unattended? I know I could probably accomplish this with forever for now, but it would be good to have a way to have it run continuously out of the box.

**Comment by Rush** [comment]
Already implemented in RPM (DEB will follow)
