### ISSUE TITLE
support for CentOS 7

### ISSUE THREAD

**Issue by jgillich** [virtkick/virtkick#78]
I did this to install everything (based on the CentOS 6 setup):
```
sudo yum install http://download.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-2.noarch.rpm
sudo yum install @development libvirt libvirt-python wget man python-pip sqlite-devel libxml2-python libxml2-devel libxslt-devel
systemctl enable libvirtd
systemctl start libvirtd

git clone https://github.com/virtkick/virtkick-starter.git
virtkick-starter/virtkick-start -dim
```
After waiting a few minutes (the entire rails repository, really? :wink:), I clicked on setup and got the following error:
```
["hostname", "name"]
Extracted source (around line #27):

errors = response.parsed_response['errors']
if errors and errors.size > 0
raise Errors, errors // <- here
end
response = response.parsed_response['response'] || {}
```
Stack trace: https://gist.github.com/jgillich/f8166aab496b94bbb8ef

**Comment by Rush** [comment]
Seems that virtkick installs out of the box on a fresh CentOS7. Tested on DigitalOcean. It has been possible thanks to your feedback dear contributors. :)
