### ISSUE TITLE
signify terminal/vnc container status

### ISSUE THREAD

**Issue by Rush** [virtkick/virtkick#86]
There are a couple of statuses:
* focused / unfocused
`.console-window` gets `focused` class when input is taken
* paused 
VNC is stuck then, perhaps some overlay could be shown to indicate the machine is paused, I intend to add some `paused` class

**Comment by malps13** [comment]
This has been fixes by virtkick/virtkick-webapp#4 and virtkick/virtkick-webapp#5.
